// Code generated by /tools/cmd/generatelisteners.go; DO NOT EDIT.
//go:generate go run ../../tools/cmd/generatelisteners.go

package listeners

import (
	"encoding/json"
	"fmt"
	"github.com/TicketsBot-cloud/gdl/gateway/payloads"
	"github.com/TicketsBot-cloud/gdl/gateway/payloads/events"
	"github.com/TicketsBot-cloud/worker"
	"github.com/getsentry/sentry-go"
)

var (
	ApplicationCommandPermissionsUpdateListeners = []func(*worker.Context, events.ApplicationCommandPermissionsUpdate){}
	AutoModerationActionExecutionListeners       = []func(*worker.Context, events.AutoModerationActionExecution){}
	AutoModerationRuleCreateListeners            = []func(*worker.Context, events.AutoModerationRuleCreate){}
	AutoModerationRuleDeleteListeners            = []func(*worker.Context, events.AutoModerationRuleDelete){}
	AutoModerationRuleUpdateListeners            = []func(*worker.Context, events.AutoModerationRuleUpdate){}
	ChannelCreateListeners                       = []func(*worker.Context, events.ChannelCreate){}
	ChannelDeleteListeners                       = []func(*worker.Context, events.ChannelDelete){}
	ChannelInfoListeners                         = []func(*worker.Context, events.ChannelInfo){}
	ChannelPinsUpdateListeners                   = []func(*worker.Context, events.ChannelPinsUpdate){}
	ChannelUpdateListeners                       = []func(*worker.Context, events.ChannelUpdate){}
	EntitlementCreateListeners                   = []func(*worker.Context, events.EntitlementCreate){}
	EntitlementDeleteListeners                   = []func(*worker.Context, events.EntitlementDelete){}
	EntitlementUpdateListeners                   = []func(*worker.Context, events.EntitlementUpdate){}
	GuildAuditLogEntryCreateListeners            = []func(*worker.Context, events.GuildAuditLogEntryCreate){}
	GuildBanAddListeners                         = []func(*worker.Context, events.GuildBanAdd){}
	GuildBanRemoveListeners                      = []func(*worker.Context, events.GuildBanRemove){}
	GuildCreateListeners                         = []func(*worker.Context, events.GuildCreate){}
	GuildDeleteListeners                         = []func(*worker.Context, events.GuildDelete){}
	GuildEmojisUpdateListeners                   = []func(*worker.Context, events.GuildEmojisUpdate){}
	GuildIntegrationsUpdateListeners             = []func(*worker.Context, events.GuildIntegrationsUpdate){}
	GuildMemberAddListeners                      = []func(*worker.Context, events.GuildMemberAdd){}
	GuildMemberRemoveListeners                   = []func(*worker.Context, events.GuildMemberRemove){}
	GuildMemberUpdateListeners                   = []func(*worker.Context, events.GuildMemberUpdate){}
	GuildMembersChunkListeners                   = []func(*worker.Context, events.GuildMembersChunk){}
	GuildRoleCreateListeners                     = []func(*worker.Context, events.GuildRoleCreate){}
	GuildRoleDeleteListeners                     = []func(*worker.Context, events.GuildRoleDelete){}
	GuildRoleUpdateListeners                     = []func(*worker.Context, events.GuildRoleUpdate){}
	GuildScheduledEventCreateListeners           = []func(*worker.Context, events.GuildScheduledEventCreate){}
	GuildScheduledEventDeleteListeners           = []func(*worker.Context, events.GuildScheduledEventDelete){}
	GuildScheduledEventUpdateListeners           = []func(*worker.Context, events.GuildScheduledEventUpdate){}
	GuildScheduledEventUserAddListeners          = []func(*worker.Context, events.GuildScheduledEventUserAdd){}
	GuildScheduledEventUserRemoveListeners       = []func(*worker.Context, events.GuildScheduledEventUserRemove){}
	GuildSoundboardSoundCreateListeners          = []func(*worker.Context, events.GuildSoundboardSoundCreate){}
	GuildSoundboardSoundDeleteListeners          = []func(*worker.Context, events.GuildSoundboardSoundDelete){}
	GuildSoundboardSoundUpdateListeners          = []func(*worker.Context, events.GuildSoundboardSoundUpdate){}
	GuildSoundboardSoundsUpdateListeners         = []func(*worker.Context, events.GuildSoundboardSoundsUpdate){}
	GuildStickersUpdateListeners                 = []func(*worker.Context, events.GuildStickersUpdate){}
	GuildUpdateListeners                         = []func(*worker.Context, events.GuildUpdate){}
	IntegrationCreateListeners                   = []func(*worker.Context, events.IntegrationCreate){}
	IntegrationDeleteListeners                   = []func(*worker.Context, events.IntegrationDelete){}
	IntegrationUpdateListeners                   = []func(*worker.Context, events.IntegrationUpdate){}
	InvalidSessionListeners                      = []func(*worker.Context, events.InvalidSession){}
	InviteCreateListeners                        = []func(*worker.Context, events.InviteCreate){}
	InviteDeleteListeners                        = []func(*worker.Context, events.InviteDelete){}
	MessageCreateListeners                       = []func(*worker.Context, events.MessageCreate){}
	MessageDeleteListeners                       = []func(*worker.Context, events.MessageDelete){}
	MessageDeleteBulkListeners                   = []func(*worker.Context, events.MessageDeleteBulk){}
	MessagePollVoteAddListeners                  = []func(*worker.Context, events.MessagePollVoteAdd){}
	MessagePollVoteRemoveListeners               = []func(*worker.Context, events.MessagePollVoteRemove){}
	MessageReactionAddListeners                  = []func(*worker.Context, events.MessageReactionAdd){}
	MessageReactionRemoveListeners               = []func(*worker.Context, events.MessageReactionRemove){}
	MessageReactionRemoveAllListeners            = []func(*worker.Context, events.MessageReactionRemoveAll){}
	MessageReactionRemoveEmojiListeners          = []func(*worker.Context, events.MessageReactionRemoveEmoji){}
	MessageUpdateListeners                       = []func(*worker.Context, events.MessageUpdate){}
	PresenceUpdateListeners                      = []func(*worker.Context, events.PresenceUpdate){}
	ReadyListeners                               = []func(*worker.Context, events.Ready){}
	ReconnectListeners                           = []func(*worker.Context, events.Reconnect){}
	ResumedListeners                             = []func(*worker.Context, events.Resumed){}
	SoundboardSoundsListeners                    = []func(*worker.Context, events.SoundboardSounds){}
	StageInstanceCreateListeners                 = []func(*worker.Context, events.StageInstanceCreate){}
	StageInstanceDeleteListeners                 = []func(*worker.Context, events.StageInstanceDelete){}
	StageInstanceUpdateListeners                 = []func(*worker.Context, events.StageInstanceUpdate){}
	SubscriptionCreateListeners                  = []func(*worker.Context, events.SubscriptionCreate){}
	SubscriptionDeleteListeners                  = []func(*worker.Context, events.SubscriptionDelete){}
	SubscriptionUpdateListeners                  = []func(*worker.Context, events.SubscriptionUpdate){}
	ThreadCreateListeners                        = []func(*worker.Context, events.ThreadCreate){}
	ThreadDeleteListeners                        = []func(*worker.Context, events.ThreadDelete){}
	ThreadListSyncListeners                      = []func(*worker.Context, events.ThreadListSync){}
	ThreadMemberUpdateListeners                  = []func(*worker.Context, events.ThreadMemberUpdate){}
	ThreadMembersUpdateListeners                 = []func(*worker.Context, events.ThreadMembersUpdate){}
	ThreadUpdateListeners                        = []func(*worker.Context, events.ThreadUpdate){}
	TypingStartListeners                         = []func(*worker.Context, events.TypingStart){}
	UserUpdateListeners                          = []func(*worker.Context, events.UserUpdate){}
	VoiceChannelEffectSendListeners              = []func(*worker.Context, events.VoiceChannelEffectSend){}
	VoiceChannelStartTimeUpdateListeners         = []func(*worker.Context, events.VoiceChannelStartTimeUpdate){}
	VoiceChannelStatusUpdateListeners            = []func(*worker.Context, events.VoiceChannelStatusUpdate){}
	VoiceServerUpdateListeners                   = []func(*worker.Context, events.VoiceServerUpdate){}
	VoiceStateUpdateListeners                    = []func(*worker.Context, events.VoiceStateUpdate){}
	WebhooksUpdateListeners                      = []func(*worker.Context, events.WebhooksUpdate){}
)

func HandleEvent(c *worker.Context, span *sentry.Span, payload payloads.Payload) error {
	if payload.Opcode != 0 { // Dispatch
		return fmt.Errorf("HandleEvent called with non-dispatch op-code: %d", payload.Opcode)
	}

	switch events.EventType(payload.EventName) {

	case events.APPLICATION_COMMAND_PERMISSIONS_UPDATE:
		var event events.ApplicationCommandPermissionsUpdate
		if err := json.Unmarshal(payload.Data, &event); err != nil {
			return err
		}

		for _, listener := range ApplicationCommandPermissionsUpdateListeners {
			listener(c, event)
		}

	case events.AUTO_MODERATION_ACTION_EXECUTION:
		var event events.AutoModerationActionExecution
		if err := json.Unmarshal(payload.Data, &event); err != nil {
			return err
		}

		for _, listener := range AutoModerationActionExecutionListeners {
			listener(c, event)
		}

	case events.AUTO_MODERATION_RULE_CREATE:
		var event events.AutoModerationRuleCreate
		if err := json.Unmarshal(payload.Data, &event); err != nil {
			return err
		}

		for _, listener := range AutoModerationRuleCreateListeners {
			listener(c, event)
		}

	case events.AUTO_MODERATION_RULE_DELETE:
		var event events.AutoModerationRuleDelete
		if err := json.Unmarshal(payload.Data, &event); err != nil {
			return err
		}

		for _, listener := range AutoModerationRuleDeleteListeners {
			listener(c, event)
		}

	case events.AUTO_MODERATION_RULE_UPDATE:
		var event events.AutoModerationRuleUpdate
		if err := json.Unmarshal(payload.Data, &event); err != nil {
			return err
		}

		for _, listener := range AutoModerationRuleUpdateListeners {
			listener(c, event)
		}

	case events.CHANNEL_CREATE:
		var event events.ChannelCreate
		if err := json.Unmarshal(payload.Data, &event); err != nil {
			return err
		}

		for _, listener := range ChannelCreateListeners {
			listener(c, event)
		}

	case events.CHANNEL_DELETE:
		var event events.ChannelDelete
		if err := json.Unmarshal(payload.Data, &event); err != nil {
			return err
		}

		for _, listener := range ChannelDeleteListeners {
			listener(c, event)
		}

	case events.CHANNEL_INFO:
		var event events.ChannelInfo
		if err := json.Unmarshal(payload.Data, &event); err != nil {
			return err
		}

		for _, listener := range ChannelInfoListeners {
			listener(c, event)
		}

	case events.CHANNEL_PINS_UPDATE:
		var event events.ChannelPinsUpdate
		if err := json.Unmarshal(payload.Data, &event); err != nil {
			return err
		}

		for _, listener := range ChannelPinsUpdateListeners {
			listener(c, event)
		}

	case events.CHANNEL_UPDATE:
		var event events.ChannelUpdate
		if err := json.Unmarshal(payload.Data, &event); err != nil {
			return err
		}

		for _, listener := range ChannelUpdateListeners {
			listener(c, event)
		}

	case events.ENTITLEMENT_CREATE:
		var event events.EntitlementCreate
		if err := json.Unmarshal(payload.Data, &event); err != nil {
			return err
		}

		for _, listener := range EntitlementCreateListeners {
			listener(c, event)
		}

	case events.ENTITLEMENT_DELETE:
		var event events.EntitlementDelete
		if err := json.Unmarshal(payload.Data, &event); err != nil {
			return err
		}

		for _, listener := range EntitlementDeleteListeners {
			listener(c, event)
		}

	case events.ENTITLEMENT_UPDATE:
		var event events.EntitlementUpdate
		if err := json.Unmarshal(payload.Data, &event); err != nil {
			return err
		}

		for _, listener := range EntitlementUpdateListeners {
			listener(c, event)
		}

	case events.GUILD_AUDIT_LOG_ENTRY_CREATE:
		var event events.GuildAuditLogEntryCreate
		if err := json.Unmarshal(payload.Data, &event); err != nil {
			return err
		}

		for _, listener := range GuildAuditLogEntryCreateListeners {
			listener(c, event)
		}

	case events.GUILD_BAN_ADD:
		var event events.GuildBanAdd
		if err := json.Unmarshal(payload.Data, &event); err != nil {
			return err
		}

		for _, listener := range GuildBanAddListeners {
			listener(c, event)
		}

	case events.GUILD_BAN_REMOVE:
		var event events.GuildBanRemove
		if err := json.Unmarshal(payload.Data, &event); err != nil {
			return err
		}

		for _, listener := range GuildBanRemoveListeners {
			listener(c, event)
		}

	case events.GUILD_CREATE:
		var event events.GuildCreate
		if err := json.Unmarshal(payload.Data, &event); err != nil {
			return err
		}

		for _, listener := range GuildCreateListeners {
			listener(c, event)
		}

	case events.GUILD_DELETE:
		var event events.GuildDelete
		if err := json.Unmarshal(payload.Data, &event); err != nil {
			return err
		}

		for _, listener := range GuildDeleteListeners {
			listener(c, event)
		}

	case events.GUILD_EMOJIS_UPDATE:
		var event events.GuildEmojisUpdate
		if err := json.Unmarshal(payload.Data, &event); err != nil {
			return err
		}

		for _, listener := range GuildEmojisUpdateListeners {
			listener(c, event)
		}

	case events.GUILD_INTEGRATIONS_UPDATE:
		var event events.GuildIntegrationsUpdate
		if err := json.Unmarshal(payload.Data, &event); err != nil {
			return err
		}

		for _, listener := range GuildIntegrationsUpdateListeners {
			listener(c, event)
		}

	case events.GUILD_MEMBER_ADD:
		var event events.GuildMemberAdd
		if err := json.Unmarshal(payload.Data, &event); err != nil {
			return err
		}

		for _, listener := range GuildMemberAddListeners {
			listener(c, event)
		}

	case events.GUILD_MEMBER_REMOVE:
		var event events.GuildMemberRemove
		if err := json.Unmarshal(payload.Data, &event); err != nil {
			return err
		}

		for _, listener := range GuildMemberRemoveListeners {
			listener(c, event)
		}

	case events.GUILD_MEMBER_UPDATE:
		var event events.GuildMemberUpdate
		if err := json.Unmarshal(payload.Data, &event); err != nil {
			return err
		}

		for _, listener := range GuildMemberUpdateListeners {
			listener(c, event)
		}

	case events.GUILD_MEMBERS_CHUNK:
		var event events.GuildMembersChunk
		if err := json.Unmarshal(payload.Data, &event); err != nil {
			return err
		}

		for _, listener := range GuildMembersChunkListeners {
			listener(c, event)
		}

	case events.GUILD_ROLE_CREATE:
		var event events.GuildRoleCreate
		if err := json.Unmarshal(payload.Data, &event); err != nil {
			return err
		}

		for _, listener := range GuildRoleCreateListeners {
			listener(c, event)
		}

	case events.GUILD_ROLE_DELETE:
		var event events.GuildRoleDelete
		if err := json.Unmarshal(payload.Data, &event); err != nil {
			return err
		}

		for _, listener := range GuildRoleDeleteListeners {
			listener(c, event)
		}

	case events.GUILD_ROLE_UPDATE:
		var event events.GuildRoleUpdate
		if err := json.Unmarshal(payload.Data, &event); err != nil {
			return err
		}

		for _, listener := range GuildRoleUpdateListeners {
			listener(c, event)
		}

	case events.GUILD_SCHEDULED_EVENT_CREATE:
		var event events.GuildScheduledEventCreate
		if err := json.Unmarshal(payload.Data, &event); err != nil {
			return err
		}

		for _, listener := range GuildScheduledEventCreateListeners {
			listener(c, event)
		}

	case events.GUILD_SCHEDULED_EVENT_DELETE:
		var event events.GuildScheduledEventDelete
		if err := json.Unmarshal(payload.Data, &event); err != nil {
			return err
		}

		for _, listener := range GuildScheduledEventDeleteListeners {
			listener(c, event)
		}

	case events.GUILD_SCHEDULED_EVENT_UPDATE:
		var event events.GuildScheduledEventUpdate
		if err := json.Unmarshal(payload.Data, &event); err != nil {
			return err
		}

		for _, listener := range GuildScheduledEventUpdateListeners {
			listener(c, event)
		}

	case events.GUILD_SCHEDULED_EVENT_USER_ADD:
		var event events.GuildScheduledEventUserAdd
		if err := json.Unmarshal(payload.Data, &event); err != nil {
			return err
		}

		for _, listener := range GuildScheduledEventUserAddListeners {
			listener(c, event)
		}

	case events.GUILD_SCHEDULED_EVENT_USER_REMOVE:
		var event events.GuildScheduledEventUserRemove
		if err := json.Unmarshal(payload.Data, &event); err != nil {
			return err
		}

		for _, listener := range GuildScheduledEventUserRemoveListeners {
			listener(c, event)
		}

	case events.GUILD_SOUNDBOARD_SOUND_CREATE:
		var event events.GuildSoundboardSoundCreate
		if err := json.Unmarshal(payload.Data, &event); err != nil {
			return err
		}

		for _, listener := range GuildSoundboardSoundCreateListeners {
			listener(c, event)
		}

	case events.GUILD_SOUNDBOARD_SOUND_DELETE:
		var event events.GuildSoundboardSoundDelete
		if err := json.Unmarshal(payload.Data, &event); err != nil {
			return err
		}

		for _, listener := range GuildSoundboardSoundDeleteListeners {
			listener(c, event)
		}

	case events.GUILD_SOUNDBOARD_SOUND_UPDATE:
		var event events.GuildSoundboardSoundUpdate
		if err := json.Unmarshal(payload.Data, &event); err != nil {
			return err
		}

		for _, listener := range GuildSoundboardSoundUpdateListeners {
			listener(c, event)
		}

	case events.GUILD_SOUNDBOARD_SOUNDS_UPDATE:
		var event events.GuildSoundboardSoundsUpdate
		if err := json.Unmarshal(payload.Data, &event); err != nil {
			return err
		}

		for _, listener := range GuildSoundboardSoundsUpdateListeners {
			listener(c, event)
		}

	case events.GUILD_STICKERS_UPDATE:
		var event events.GuildStickersUpdate
		if err := json.Unmarshal(payload.Data, &event); err != nil {
			return err
		}

		for _, listener := range GuildStickersUpdateListeners {
			listener(c, event)
		}

	case events.GUILD_UPDATE:
		var event events.GuildUpdate
		if err := json.Unmarshal(payload.Data, &event); err != nil {
			return err
		}

		for _, listener := range GuildUpdateListeners {
			listener(c, event)
		}

	case events.INTEGRATION_CREATE:
		var event events.IntegrationCreate
		if err := json.Unmarshal(payload.Data, &event); err != nil {
			return err
		}

		for _, listener := range IntegrationCreateListeners {
			listener(c, event)
		}

	case events.INTEGRATION_DELETE:
		var event events.IntegrationDelete
		if err := json.Unmarshal(payload.Data, &event); err != nil {
			return err
		}

		for _, listener := range IntegrationDeleteListeners {
			listener(c, event)
		}

	case events.INTEGRATION_UPDATE:
		var event events.IntegrationUpdate
		if err := json.Unmarshal(payload.Data, &event); err != nil {
			return err
		}

		for _, listener := range IntegrationUpdateListeners {
			listener(c, event)
		}

	case events.INVALID_SESSION:
		var event events.InvalidSession
		if err := json.Unmarshal(payload.Data, &event); err != nil {
			return err
		}

		for _, listener := range InvalidSessionListeners {
			listener(c, event)
		}

	case events.INVITE_CREATE:
		var event events.InviteCreate
		if err := json.Unmarshal(payload.Data, &event); err != nil {
			return err
		}

		for _, listener := range InviteCreateListeners {
			listener(c, event)
		}

	case events.INVITE_DELETE:
		var event events.InviteDelete
		if err := json.Unmarshal(payload.Data, &event); err != nil {
			return err
		}

		for _, listener := range InviteDeleteListeners {
			listener(c, event)
		}

	case events.MESSAGE_CREATE:
		var event events.MessageCreate
		if err := json.Unmarshal(payload.Data, &event); err != nil {
			return err
		}

		for _, listener := range MessageCreateListeners {
			listener(c, event)
		}

	case events.MESSAGE_DELETE:
		var event events.MessageDelete
		if err := json.Unmarshal(payload.Data, &event); err != nil {
			return err
		}

		for _, listener := range MessageDeleteListeners {
			listener(c, event)
		}

	case events.MESSAGE_DELETE_BULK:
		var event events.MessageDeleteBulk
		if err := json.Unmarshal(payload.Data, &event); err != nil {
			return err
		}

		for _, listener := range MessageDeleteBulkListeners {
			listener(c, event)
		}

	case events.MESSAGE_POLL_VOTE_ADD:
		var event events.MessagePollVoteAdd
		if err := json.Unmarshal(payload.Data, &event); err != nil {
			return err
		}

		for _, listener := range MessagePollVoteAddListeners {
			listener(c, event)
		}

	case events.MESSAGE_POLL_VOTE_REMOVE:
		var event events.MessagePollVoteRemove
		if err := json.Unmarshal(payload.Data, &event); err != nil {
			return err
		}

		for _, listener := range MessagePollVoteRemoveListeners {
			listener(c, event)
		}

	case events.MESSAGE_REACTION_ADD:
		var event events.MessageReactionAdd
		if err := json.Unmarshal(payload.Data, &event); err != nil {
			return err
		}

		for _, listener := range MessageReactionAddListeners {
			listener(c, event)
		}

	case events.MESSAGE_REACTION_REMOVE:
		var event events.MessageReactionRemove
		if err := json.Unmarshal(payload.Data, &event); err != nil {
			return err
		}

		for _, listener := range MessageReactionRemoveListeners {
			listener(c, event)
		}

	case events.MESSAGE_REACTION_REMOVE_ALL:
		var event events.MessageReactionRemoveAll
		if err := json.Unmarshal(payload.Data, &event); err != nil {
			return err
		}

		for _, listener := range MessageReactionRemoveAllListeners {
			listener(c, event)
		}

	case events.MESSAGE_REACTION_REMOVE_EMOJI:
		var event events.MessageReactionRemoveEmoji
		if err := json.Unmarshal(payload.Data, &event); err != nil {
			return err
		}

		for _, listener := range MessageReactionRemoveEmojiListeners {
			listener(c, event)
		}

	case events.MESSAGE_UPDATE:
		var event events.MessageUpdate
		if err := json.Unmarshal(payload.Data, &event); err != nil {
			return err
		}

		for _, listener := range MessageUpdateListeners {
			listener(c, event)
		}

	case events.PRESENCE_UPDATE:
		var event events.PresenceUpdate
		if err := json.Unmarshal(payload.Data, &event); err != nil {
			return err
		}

		for _, listener := range PresenceUpdateListeners {
			listener(c, event)
		}

	case events.READY:
		var event events.Ready
		if err := json.Unmarshal(payload.Data, &event); err != nil {
			return err
		}

		for _, listener := range ReadyListeners {
			listener(c, event)
		}

	case events.RECONNECT:
		var event events.Reconnect
		if err := json.Unmarshal(payload.Data, &event); err != nil {
			return err
		}

		for _, listener := range ReconnectListeners {
			listener(c, event)
		}

	case events.RESUMED:
		var event events.Resumed
		if err := json.Unmarshal(payload.Data, &event); err != nil {
			return err
		}

		for _, listener := range ResumedListeners {
			listener(c, event)
		}

	case events.SOUNDBOARD_SOUNDS:
		var event events.SoundboardSounds
		if err := json.Unmarshal(payload.Data, &event); err != nil {
			return err
		}

		for _, listener := range SoundboardSoundsListeners {
			listener(c, event)
		}

	case events.STAGE_INSTANCE_CREATE:
		var event events.StageInstanceCreate
		if err := json.Unmarshal(payload.Data, &event); err != nil {
			return err
		}

		for _, listener := range StageInstanceCreateListeners {
			listener(c, event)
		}

	case events.STAGE_INSTANCE_DELETE:
		var event events.StageInstanceDelete
		if err := json.Unmarshal(payload.Data, &event); err != nil {
			return err
		}

		for _, listener := range StageInstanceDeleteListeners {
			listener(c, event)
		}

	case events.STAGE_INSTANCE_UPDATE:
		var event events.StageInstanceUpdate
		if err := json.Unmarshal(payload.Data, &event); err != nil {
			return err
		}

		for _, listener := range StageInstanceUpdateListeners {
			listener(c, event)
		}

	case events.SUBSCRIPTION_CREATE:
		var event events.SubscriptionCreate
		if err := json.Unmarshal(payload.Data, &event); err != nil {
			return err
		}

		for _, listener := range SubscriptionCreateListeners {
			listener(c, event)
		}

	case events.SUBSCRIPTION_DELETE:
		var event events.SubscriptionDelete
		if err := json.Unmarshal(payload.Data, &event); err != nil {
			return err
		}

		for _, listener := range SubscriptionDeleteListeners {
			listener(c, event)
		}

	case events.SUBSCRIPTION_UPDATE:
		var event events.SubscriptionUpdate
		if err := json.Unmarshal(payload.Data, &event); err != nil {
			return err
		}

		for _, listener := range SubscriptionUpdateListeners {
			listener(c, event)
		}

	case events.THREAD_CREATE:
		var event events.ThreadCreate
		if err := json.Unmarshal(payload.Data, &event); err != nil {
			return err
		}

		for _, listener := range ThreadCreateListeners {
			listener(c, event)
		}

	case events.THREAD_DELETE:
		var event events.ThreadDelete
		if err := json.Unmarshal(payload.Data, &event); err != nil {
			return err
		}

		for _, listener := range ThreadDeleteListeners {
			listener(c, event)
		}

	case events.THREAD_LIST_SYNC:
		var event events.ThreadListSync
		if err := json.Unmarshal(payload.Data, &event); err != nil {
			return err
		}

		for _, listener := range ThreadListSyncListeners {
			listener(c, event)
		}

	case events.THREAD_MEMBER_UPDATE:
		var event events.ThreadMemberUpdate
		if err := json.Unmarshal(payload.Data, &event); err != nil {
			return err
		}

		for _, listener := range ThreadMemberUpdateListeners {
			listener(c, event)
		}

	case events.THREAD_MEMBERS_UPDATE:
		var event events.ThreadMembersUpdate
		if err := json.Unmarshal(payload.Data, &event); err != nil {
			return err
		}

		for _, listener := range ThreadMembersUpdateListeners {
			listener(c, event)
		}

	case events.THREAD_UPDATE:
		var event events.ThreadUpdate
		if err := json.Unmarshal(payload.Data, &event); err != nil {
			return err
		}

		for _, listener := range ThreadUpdateListeners {
			listener(c, event)
		}

	case events.TYPING_START:
		var event events.TypingStart
		if err := json.Unmarshal(payload.Data, &event); err != nil {
			return err
		}

		for _, listener := range TypingStartListeners {
			listener(c, event)
		}

	case events.USER_UPDATE:
		var event events.UserUpdate
		if err := json.Unmarshal(payload.Data, &event); err != nil {
			return err
		}

		for _, listener := range UserUpdateListeners {
			listener(c, event)
		}

	case events.VOICE_CHANNEL_EFFECT_SEND:
		var event events.VoiceChannelEffectSend
		if err := json.Unmarshal(payload.Data, &event); err != nil {
			return err
		}

		for _, listener := range VoiceChannelEffectSendListeners {
			listener(c, event)
		}

	case events.VOICE_CHANNEL_START_TIME_UPDATE:
		var event events.VoiceChannelStartTimeUpdate
		if err := json.Unmarshal(payload.Data, &event); err != nil {
			return err
		}

		for _, listener := range VoiceChannelStartTimeUpdateListeners {
			listener(c, event)
		}

	case events.VOICE_CHANNEL_STATUS_UPDATE:
		var event events.VoiceChannelStatusUpdate
		if err := json.Unmarshal(payload.Data, &event); err != nil {
			return err
		}

		for _, listener := range VoiceChannelStatusUpdateListeners {
			listener(c, event)
		}

	case events.VOICE_SERVER_UPDATE:
		var event events.VoiceServerUpdate
		if err := json.Unmarshal(payload.Data, &event); err != nil {
			return err
		}

		for _, listener := range VoiceServerUpdateListeners {
			listener(c, event)
		}

	case events.VOICE_STATE_UPDATE:
		var event events.VoiceStateUpdate
		if err := json.Unmarshal(payload.Data, &event); err != nil {
			return err
		}

		for _, listener := range VoiceStateUpdateListeners {
			listener(c, event)
		}

	case events.WEBHOOKS_UPDATE:
		var event events.WebhooksUpdate
		if err := json.Unmarshal(payload.Data, &event); err != nil {
			return err
		}

		for _, listener := range WebhooksUpdateListeners {
			listener(c, event)
		}

	default:
		return fmt.Errorf("Unknown event type: %s", payload.EventName)
	}

	return nil
}
